
          
# This file is generated by scripts/create_appid_include.py
# It includes all the appIds that are available
# generated from the documentation/lusee_appIds.md file.

# AppIds
# X; Priority:  5     
AppID_Read_Response = 0x0200

# No description available; Priority:  5     
AppID_Reset_Request = 0x0201

# X; Priority:  5     
AppID_Registers_RB = 0x0205

# No description available; Priority:  5     
AppID_uC_Housekeeping = 0x0206

# No description available; Priority:  5     
AppID_End_Of_Sequence = 0x0207

# X; Priority:  5     
AppID_uC_Bootloader = 0x0208

# No description available; Priority:  5     
AppID_uC_Start = 0x0209

# No description available; Priority:  NONE  
AppID_uC_Heartbeat = 0x020A

# No description available; Priority:  5     
AppID_uC_Restored = 0x020B

# No description available; Priority:  5     
AppID_Watchdog = 0x020C

# No description available; Priority:  5     
AppID_Reserved1 = 0x020D

# No description available; Priority:  5     
AppID_Reserved2 = 0x020E

# No description available; Priority:  5     
AppID_MetaData = 0x020F

# No description available; Priority:  6     
AppID_SpectraHigh = 0x0210

# No description available; Priority:  7     
AppID_SpectraMed = 0x0220

# No description available; Priority:  8     
AppID_SpectraLow = 0x0230

# No description available; Priority:  6     
AppID_SpectraTRHigh = 0x0240

# No description available; Priority:  7     
AppID_SpectraTRMed = 0x0250

# No description available; Priority:  8     
AppID_SpectraTRLow = 0x0260

# No description available; Priority:  6     
AppID_ZoomSpectra = 0x0270

# No description available; Priority:  5     
AppID_Calibrator_MetaData = 0x0280

# No description available; Priority:  6     
AppID_Calibrator_Data = 0x0281

# No description available; Priority:  9     
AppID_Calibrator_RawPFB = 0x0284

# No description available; Priority:  9     
AppID_Calibrator_Debug = 0x028C

# No description available; Priority:  6     
AppID_SpectraGrimm = 0x02A0

# X; Priority:  9     
AppID_FW_DirectSpectrum = 0x02E0

# X; Priority:  6     
AppID_RawADC = 0x02F0

# No description available; Priority:  6     
AppID_RawADC_Meta = 0x02FA

# X; Priority:  5     
AppID_FW_Watchdog = 0x02FF

