name: Run standalone Python Tests

on:
  push:
    branches:
      - standalone_tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Clone coreloop repo
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        owner: 'lusee-night'
        repository: 'coreloop'

    - name: Compile coreloop library
      run: |
        cd coreloop
        git checkout encode_32_16_an
        mkdir build
        cd build
        cmake ..
        make cl_utils
        cd ../..

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install pytest
      run: pip install numpy pytest

    - name: Set CORELOOP_DIR environment variable
      run: echo "CORELOOP_DIR=$GITHUB_WORKSPACE/coreloop" >> $GITHUB_ENV

    - name: Run Python tests with pytest
      run: pytest test/standalone/
      env:
        CORELOOP_DIR: ${{ env.CORELOOP_DIR }}
